spring.application.name=algo-tutor-be

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:onlinejudge}
spring.datasource.username=${DB_USER:ojuser}
spring.datasource.password=${DB_PASSWORD:ojpass}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop