spring.application.name=algo-tutor-be

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/onlinejudge
spring.datasource.username=ojuser
spring.datasource.password=ojpass
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop