CREATE TABLE IF NOT EXISTS ai_conversation
(
    id         UUID         NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    UUID         NOT NULL,
    lesson_id  BIGINT,
    title      VARCHAR(255),
    provider   VARCHAR(255) NOT NULL,
    type       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_ai_conversation PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS ai_conversation_state
(
    id                     UUID NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    conversation_id        UUID,
    problem_id             BIGINT,
    lesson_id              BIGINT,
    lesson_slug            VARCHAR(255),
    hint_level             INTEGER,
    solution_unlocked      BOOLEAN,
    current_intent         VARCHAR(255),
    last_code_hash         VARCHAR(255),
    last_submission_id     BIGINT,
    last_failed_test_case  TEXT,
    last_discussed_concept VARCHAR(255),
    CONSTRAINT pk_ai_conversation_state PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS ai_messages
(
    id              UUID         NOT NULL,
    conversation_id UUID         NOT NULL,
    user_id         UUID         NOT NULL,
    role            VARCHAR(255) NOT NULL,
    content         TEXT         NOT NULL,
    mode            VARCHAR(255),
    token_input     INTEGER,
    token_output    INTEGER,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_ai_messages PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS coding_lesson
(
    id                   BIGINT  NOT NULL,
    statement            TEXT    NOT NULL,
    base_time_limit_ms   INTEGER NOT NULL,
    base_memory_limit_mb INTEGER NOT NULL,
    starter_code         JSONB   NOT NULL,
    constraints          JSONB,
    hints                JSONB,
    examples             JSONB,
    CONSTRAINT pk_codinglesson PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS editorials
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    coding_lesson_id BIGINT                                  NOT NULL,
    language         VARCHAR(50)                             NOT NULL,
    source_code      TEXT                                    NOT NULL,
    CONSTRAINT pk_editorials PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS enrollments
(
    id                  UUID        NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    user_id             UUID        NOT NULL,
    learning_path_id    BIGINT      NOT NULL,
    progress_percentage DOUBLE PRECISION,
    enrolled_at         TIMESTAMP WITHOUT TIME ZONE,
    completed_at        TIMESTAMP WITHOUT TIME ZONE,
    status              VARCHAR(20) NOT NULL,
    CONSTRAINT pk_enrollments PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS learning_paths
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    slug          VARCHAR(255),
    level         VARCHAR(255),
    description   VARCHAR(255),
    goal          VARCHAR(255),
    thumbnail_url VARCHAR(255),
    is_published  BOOLEAN                                 NOT NULL,
    is_premium    BOOLEAN,
    CONSTRAINT pk_learning_paths PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS lesson_progresses
(
    id            UUID        NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    user_id       UUID        NOT NULL,
    lesson_id     BIGINT      NOT NULL,
    enrollment_id UUID        NOT NULL,
    is_completed  BOOLEAN     NOT NULL,
    status        VARCHAR(20) NOT NULL,
    completed_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lesson_progresses PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS lessons
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    title         VARCHAR(200)                            NOT NULL,
    slug          VARCHAR(255),
    type          VARCHAR(20)                             NOT NULL,
    display_order INTEGER                                 NOT NULL,
    difficulty    VARCHAR(20),
    is_published  BOOLEAN                                 NOT NULL,
    topic_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS quiz_attempts
(
    id                 UUID    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    user_id            UUID    NOT NULL,
    quiz_id            BIGINT  NOT NULL,
    lesson_slug        VARCHAR(255),
    roadmap_slug       VARCHAR(255),
    score              FLOAT,
    is_passed          BOOLEAN NOT NULL,
    total_questions    INTEGER,
    correct_count      INTEGER,
    answers_snapshot   JSONB,
    question_results   JSONB,
    attempt_number     INTEGER,
    total_points       INTEGER,
    started_at         TIMESTAMP WITHOUT TIME ZONE,
    time_spent_seconds INTEGER,
    completed_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quiz_attempts PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS quiz_lesson
(
    id                 BIGINT NOT NULL,
    passing_score      INTEGER,
    time_limit_minutes INTEGER,
    CONSTRAINT pk_quizlesson PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS quiz_questions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    lesson_id   BIGINT                                  NOT NULL,
    question    VARCHAR(255)                            NOT NULL,
    type        VARCHAR(30)                             NOT NULL,
    order_index INTEGER                                 NOT NULL,
    points      INTEGER,
    explanation TEXT,
    choices     JSONB,
    CONSTRAINT pk_quiz_questions PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    user_id     UUID,
    token       UUID                                    NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    ipv4address VARCHAR(255),
    device_info VARCHAR(255),
    CONSTRAINT pk_refreshtokens PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    code        VARCHAR(50)                             NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS submission_detail
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    submission_id UUID,
    testcase_id   BIGINT,
    verdict       VARCHAR(255),
    time          INTEGER,
    memory        INTEGER,
    CONSTRAINT pk_submission_detail PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS submissions
(
    id                UUID   NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    version           BIGINT,
    user_id           UUID   NOT NULL,
    coding_lesson_id  BIGINT NOT NULL,
    code              TEXT   NOT NULL,
    language          VARCHAR(255),
    total_test_cases  INTEGER,
    passed_test_cases INTEGER,
    execution_time_ms INTEGER,
    memory_used_kb    INTEGER,
    compile_output    TEXT,
    status            VARCHAR(255),
    progress_updated  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_submissions PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS test_cases
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    coding_lesson_id BIGINT                                  NOT NULL,
    input_file_url   VARCHAR(255)                            NOT NULL,
    output_file_url  VARCHAR(255)                            NOT NULL,
    input_file_key   VARCHAR(255)                            NOT NULL,
    output_file_key  VARCHAR(255)                            NOT NULL,
    score_weight     INTEGER,
    is_sample        BOOLEAN,
    sort_order       INTEGER,
    CONSTRAINT pk_test_cases PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS theory_lesson
(
    id                BIGINT NOT NULL,
    content           TEXT   NOT NULL,
    estimated_minutes INTEGER,
    CONSTRAINT pk_theorylesson PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS topics
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(100)                            NOT NULL,
    description      TEXT,
    display_order    INTEGER                                 NOT NULL,
    learning_path_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_topics PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS users
(
    id            UUID         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    enabled       BOOLEAN      NOT NULL,
    block_reason  VARCHAR(255),
    avatar        VARCHAR(255),
    role_id       BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_0882f6a755f233d0e251d35ea'
          AND conrelid = 'lesson_progresses'::regclass
    ) THEN
ALTER TABLE lesson_progresses
    ADD CONSTRAINT uc_0882f6a755f233d0e251d35ea UNIQUE (user_id, lesson_id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_98919920e10e937ceff783bc2'
          AND conrelid = 'enrollments'::regclass
    ) THEN
ALTER TABLE enrollments
    ADD CONSTRAINT uc_98919920e10e937ceff783bc2 UNIQUE (user_id, learning_path_id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_lessons_slug'
          AND conrelid = 'lessons'::regclass
    ) THEN
ALTER TABLE lessons
    ADD CONSTRAINT uc_lessons_slug UNIQUE (slug);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_refreshtokens_token'
          AND conrelid = 'refresh_tokens'::regclass
    ) THEN
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refreshtokens_token UNIQUE (token);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_roles_code'
          AND conrelid = 'roles'::regclass
    ) THEN
ALTER TABLE roles
    ADD CONSTRAINT uc_roles_code UNIQUE (code);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_roles_name'
          AND conrelid = 'roles'::regclass
    ) THEN
ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_users_email'
          AND conrelid = 'users'::regclass
    ) THEN
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uc_users_username'
          AND conrelid = 'users'::regclass
    ) THEN
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ai_conversation_state_conversation_id ON ai_conversation_state (conversation_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_CODINGLESSON_ON_ID'
          AND conrelid = 'coding_lesson'::regclass
    ) THEN
ALTER TABLE coding_lesson
    ADD CONSTRAINT FK_CODINGLESSON_ON_ID FOREIGN KEY (id) REFERENCES lessons (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_EDITORIALS_ON_CODING_LESSON'
          AND conrelid = 'editorials'::regclass
    ) THEN
ALTER TABLE editorials
    ADD CONSTRAINT FK_EDITORIALS_ON_CODING_LESSON FOREIGN KEY (coding_lesson_id) REFERENCES coding_lesson (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_editorials_coding_lesson_id ON editorials (coding_lesson_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_ENROLLMENTS_ON_LEARNING_PATH'
          AND conrelid = 'enrollments'::regclass
    ) THEN
ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_LEARNING_PATH FOREIGN KEY (learning_path_id) REFERENCES learning_paths (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_enrollments_learning_path_id ON enrollments (learning_path_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_ENROLLMENTS_ON_USER'
          AND conrelid = 'enrollments'::regclass
    ) THEN
ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_LESSONS_ON_TOPIC'
          AND conrelid = 'lessons'::regclass
    ) THEN
ALTER TABLE lessons
    ADD CONSTRAINT FK_LESSONS_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topics (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lessons_topic_id ON lessons (topic_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_LESSON_PROGRESSES_ON_ENROLLMENT'
          AND conrelid = 'lesson_progresses'::regclass
    ) THEN
ALTER TABLE lesson_progresses
    ADD CONSTRAINT FK_LESSON_PROGRESSES_ON_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES enrollments (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lesson_progresses_enrollment_id ON lesson_progresses (enrollment_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_LESSON_PROGRESSES_ON_LESSON'
          AND conrelid = 'lesson_progresses'::regclass
    ) THEN
ALTER TABLE lesson_progresses
    ADD CONSTRAINT FK_LESSON_PROGRESSES_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES lessons (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lesson_progresses_lesson_id ON lesson_progresses (lesson_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_LESSON_PROGRESSES_ON_USER'
          AND conrelid = 'lesson_progresses'::regclass
    ) THEN
ALTER TABLE lesson_progresses
    ADD CONSTRAINT FK_LESSON_PROGRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_QUIZLESSON_ON_ID'
          AND conrelid = 'quiz_lesson'::regclass
    ) THEN
ALTER TABLE quiz_lesson
    ADD CONSTRAINT FK_QUIZLESSON_ON_ID FOREIGN KEY (id) REFERENCES lessons (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_QUIZ_ATTEMPTS_ON_QUIZ'
          AND conrelid = 'quiz_attempts'::regclass
    ) THEN
ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz_lesson (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_QUIZ_ATTEMPTS_ON_USER'
          AND conrelid = 'quiz_attempts'::regclass
    ) THEN
ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_QUIZ_QUESTIONS_ON_LESSON'
          AND conrelid = 'quiz_questions'::regclass
    ) THEN
ALTER TABLE quiz_questions
    ADD CONSTRAINT FK_QUIZ_QUESTIONS_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES quiz_lesson (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_REFRESHTOKENS_ON_USER'
          AND conrelid = 'refresh_tokens'::regclass
    ) THEN
ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESHTOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_SUBMISSIONS_ON_CODING_LESSON'
          AND conrelid = 'submissions'::regclass
    ) THEN
ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_CODING_LESSON FOREIGN KEY (coding_lesson_id) REFERENCES coding_lesson (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_submissions_coding_lesson_id ON submissions (coding_lesson_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_SUBMISSIONS_ON_USER'
          AND conrelid = 'submissions'::regclass
    ) THEN
ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON submissions (user_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_SUBMISSION_DETAIL_ON_SUBMISSION'
          AND conrelid = 'submission_detail'::regclass
    ) THEN
ALTER TABLE submission_detail
    ADD CONSTRAINT FK_SUBMISSION_DETAIL_ON_SUBMISSION FOREIGN KEY (submission_id) REFERENCES submissions (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_submission_detail_submission_id ON submission_detail (submission_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_SUBMISSION_DETAIL_ON_TESTCASE'
          AND conrelid = 'submission_detail'::regclass
    ) THEN
ALTER TABLE submission_detail
    ADD CONSTRAINT FK_SUBMISSION_DETAIL_ON_TESTCASE FOREIGN KEY (testcase_id) REFERENCES test_cases (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_submission_detail_testcase_id ON submission_detail (testcase_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_TEST_CASES_ON_CODING_LESSON'
          AND conrelid = 'test_cases'::regclass
    ) THEN
ALTER TABLE test_cases
    ADD CONSTRAINT FK_TEST_CASES_ON_CODING_LESSON FOREIGN KEY (coding_lesson_id) REFERENCES coding_lesson (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_test_cases_coding_lesson_id ON test_cases (coding_lesson_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_THEORYLESSON_ON_ID'
          AND conrelid = 'theory_lesson'::regclass
    ) THEN
ALTER TABLE theory_lesson
    ADD CONSTRAINT FK_THEORYLESSON_ON_ID FOREIGN KEY (id) REFERENCES lessons (id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_TOPICS_ON_LEARNING_PATH'
          AND conrelid = 'topics'::regclass
    ) THEN
ALTER TABLE topics
    ADD CONSTRAINT FK_TOPICS_ON_LEARNING_PATH FOREIGN KEY (learning_path_id) REFERENCES learning_paths (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_topics_learning_path_id ON topics (learning_path_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_USERS_ON_ROLE'
          AND conrelid = 'users'::regclass
    ) THEN
ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);
END IF;
END $$;
